name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy bandit pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with Black
      run: |
        black --check --diff workingdays tests
    - name: Check types with mypy
      run: |
        mypy workingdays
    - name: Check for security issues with Bandit
      run: |
        bandit -r workingdays
    - name: Test with pytest
      run: |
        pytest
